name: Lint

on:
  push:
    branches-ignore:
      - gh-pages
      - metakitty
  pull_request:
    branches:
      - '*'

jobs:
  msftidy:
    runs-on: ubuntu-18.04
    timeout-minutes: 40

    strategy:
      fail-fast: true
      matrix:
        ruby:
          - 2.5

    name: Lint msftidy
    steps:
      - name: Install system dependencies
        run: sudo apt-get install libpcap-dev graphviz

      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
        # Required to checkout HEAD^ and 3a046f01dae340c124dd3895e670983aef5fe0c5 for the msftidy script
        # https://github.com/actions/checkout/tree/5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f#checkout-head
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@5e4f0a10bfc39c97cd5358121291e27e5d97e09b # pin@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
        env:
          BUNDLE_WITHOUT: "coverage development pcap"

      - name: Run msftidy
        run: |
          ln -sf ../../tools/dev/pre-commit-hook.rb ./.git/hooks/post-merge
          ls -la ./.git/hooks
          ./.git/hooks/post-merge
